files:
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_000477071.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:01.961Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_000477071.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_000608681.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:17.742Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_000608681.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_006574532.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:19.076Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_006574532.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_009278212.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:00.716Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_009278212.PNG
