files:
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_044417683.PNG
    size: '17434949'
    updated: '2025-10-22T16:19:59.851Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_044417683.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_044477111.PNG
    size: '17434949'
    updated: '2025-10-22T16:20:05.007Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_044477111.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_047218263.PNG
    size: '17446941'
    updated: '2025-10-22T16:20:07.293Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_047218263.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_047223161.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:12.796Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_047223161.PNG
