files:
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_031691685.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:05.999Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_031691685.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_033918198.PNG
    size: '17447720'
    updated: '2025-10-22T16:20:15.147Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_033918198.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_036892827.PNG
    size: '17434949'
    updated: '2025-10-22T16:20:09.491Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_036892827.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_041610658.PNG
    size: '17438457'
    updated: '2025-10-22T16:20:16.389Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_041610658.PNG
