files:
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_014442174.PNG
    size: '17446927'
    updated: '2025-10-22T16:20:10.511Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_014442174.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_015141781.PNG
    size: '17434949'
    updated: '2025-10-22T16:20:08.362Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_015141781.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_027300144.PNG
    size: '17447720'
    updated: '2025-10-22T16:20:02.905Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_027300144.PNG
  - name: floor_plans/data/dummy/images/STR/APT_FP_STR_028450603.PNG
    size: '17447720'
    updated: '2025-10-22T16:20:04.047Z'
    url: >-
      https://storage.googleapis.com/decora-alpha-deno/floor_plans/data/dummy/images/STR/APT_FP_STR_028450603.PNG
